// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QaAJjpnenlY9HL-eAkrxXVIkxnSWd2Y',
    appId: '1:844151105132:web:fd417603ae0935a9d65a49',
    messagingSenderId: '844151105132',
    projectId: 'flutter-projects-228e2',
    authDomain: 'flutter-projects-228e2.firebaseapp.com',
    storageBucket: 'flutter-projects-228e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdCgwQ2BGdF51FuKt7sJIYvaxIppRilWo',
    appId: '1:844151105132:android:93009bfd12882c68d65a49',
    messagingSenderId: '844151105132',
    projectId: 'flutter-projects-228e2',
    storageBucket: 'flutter-projects-228e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMfca-3Ruk1l21u8QUtFDaNda56aHwWw',
    appId: '1:844151105132:ios:6b2862cd39f49cbbd65a49',
    messagingSenderId: '844151105132',
    projectId: 'flutter-projects-228e2',
    storageBucket: 'flutter-projects-228e2.appspot.com',
    iosClientId: '844151105132-us8c2q2huggvhs3b6bnlud7r0gbiqaca.apps.googleusercontent.com',
    iosBundleId: 'com.hjuanma.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMfca-3Ruk1l21u8QUtFDaNda56aHwWw',
    appId: '1:844151105132:ios:7c1f993697b8eb5fd65a49',
    messagingSenderId: '844151105132',
    projectId: 'flutter-projects-228e2',
    storageBucket: 'flutter-projects-228e2.appspot.com',
    iosClientId: '844151105132-gv61i2j60qle1cct09fj00hb68gjp99c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
